---
- hosts: localhost
  gather_facts: yes
  environment:
    https_proxy: "{{ lookup('env', 'HTTPS_PROXY') }}"
  vars_files:
    - defaults/main.yml

  roles:
    #  General
    - { role: debian, tags: debian }
    - { role: config_dns, tags: dns }
    - { role: install_konsole, tags: [konsole, never] }
    - { role: deepin, tags: deepin }
    - { role: install_solaar, tags: solaar }

    # Development
    - { role: install_zsh, tags: [zsh, dev] }
    - { role: config_git, tags: [git, dev] }
    - { role: install_code, tags: [code, dev] }
    - { role: install_postman, tags: [postman, dev] }
    - { role: install_directorystudio, tags: [directorystudio, dev] }
    - { role: install_robo3t, tags: [robo3t, dev] }

    # Container
    - { role: install_docker, tags: [docker, container] }
    - { role: install_kubectl, tags: [kubectl, container] }
    - { role: install_helm, tags: [helm, container] }

    # IaC
    - { role: config_ansible, tags: [ansible, iac] }
    - { role: install_packer, tags: [packer, iac] }
    - { role: install_terraform, tags: [terraform, iac] }

    # Communication
    - { role: install_teams, tags: [teams, communications] }
