- name: Install zsh
  ansible.builtin.apt:
    name: zsh
  become: yes
  when: ansible_distribution != "Archlinux"

- name: Install ohmyzsh
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  become: no
  register: ohmyzsh_rc
  failed_when: ohmyzsh_rc.rc != 0 and ohmyzsh_rc.rc != 1
  ignore_errors: true

- name: Set user shell
  ansible.builtin.user:
    name: "{{ user }}"
    shell: /bin/zsh
  become: yes

- name: Create template files
  ansible.builtin.template:
    dest: "{{ lookup('env', 'HOME') }}/{{ item.dest }}"
    src: "{{ item.src }}"
    owner: "{{ user }}"
    group: "{{ lookup('pipe', 'id -n -g') }}"
  become: no
  loop:
    - { src: 'zshrc.j2', dest: '.zshrc' }
    - { src: 'kubectl_aliases.j2', dest: '.kubectl_aliases' }
    - { src: 'my_aliases.j2', dest: '.my_aliases' }
