---
- name: Create dev directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/dev/"
    owner: "{{ user }}"
    group: "{{ lookup('pipe', 'id -n -g') }}"
    state: directory

- name: Config git gooks
  ansible.builtin.copy:
    src: files/gitconfig
    dest: "{{ lookup('env', 'HOME') }}/dev/"
    mode: preserve

- name: Create gitconfig file
  ansible.builtin.template:
    src: .gitconfig.j2
    dest: "{{ lookup('env', 'HOME') }}/.gitconfig"

- name: Install gh
  ansible.builtin.include_tasks: install_gh.yml
