---
- name: Get repo key
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present
  become: yes

- name: Add docker repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  become: yes

- name: Install docker components
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
  become: yes

- name: Add user to group
  ansible.builtin.user:
    name: "{{ user }}"
    groups: docker
    append: yes
  become: yes

- name: Create /etc/docker
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: '0644'
    owner: root
    group: root
  become: yes

- name: Create daemon.json
  ansible.builtin.template:
    dest: /etc/docker/daemon.json
    src: daemon.json.j2
  become: yes

- name: Create /usr/local/bin
  ansible.builtin.file:
    path: /usr/local/bin
    state: directory
    mode: '0755'
  become: yes

- name: Restart docker service
  ansible.builtin.systemd:
    name: docker
    state: restarted
  become: yes
  when: ansible_service_mgr | default("") == "systemd"

- name: Install dive
  ansible.builtin.apt:
    deb: https://github.com/wagoodman/dive/releases/download/v0.9.2/dive_0.9.2_linux_amd64.deb
    state: present
  become: yes
