---
- name: Create kubectx dir
  ansible.builtin.file:
    path: "/opt/kubectx/"
    owner: "{{ user }}"
    group: "{{ lookup('pipe', 'id -n -g') }}"
    state: directory
  become: yes

- name: Download kubectx packages
  ansible.builtin.git:
    repo: https://github.com/ahmetb/kubectx
    dest: /opt/kubectx
#  become: yes

- name: Create simlinks
  ansible.builtin.file:
    src: "/opt/kubectx/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  loop:
    - kubectx
    - kubens
  become: yes

- name: Create completion dir
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/completions"
    state: directory
    mode: '0755'

- name: Config autocomplete
  ansible.builtin.file:
    src: "/opt/kubectx/completion/{{ item }}.zsh"
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/completions/{{ item }}"
    state: link
  loop:
    - _kubectx
    - _kubens
