---
- ansible.builtin.set_fact:
    stern_dir: /opt/stern

- name: Create dir
  ansible.builtin.file:
    path: "{{ stern_dir }}"
    state: directory
    mode: '0755'
  become: yes

- name: Check local file
  ansible.builtin.stat:
    path: "roles/install_stern/files/stern_linux_amd64"
  register: local_file

- when: local_file.stat.exists
  ansible.builtin.copy:
    src: stern_linux_amd64
    dest: "{{ stern_dir }}/stern"
    mode: '0755'
  become: yes

- name: Download stern binary
  when: not local_file.stat.exists
  ansible.builtin.unarchive:
    src: https://github.com/stern/stern/releases/download/v1.22.0/stern_1.22.0_linux_amd64.tar.gz
    dest: "{{ stern_dir }}"
    remote_src: yes
  become: yes

- name: Change permissions
  ansible.builtin.file:
    path: "{{ stern_dir }}/stern"
    state: file
    mode: 0755
  become: yes

- name: Create simlinks
  ansible.builtin.file:
    src: "{{ stern_dir }}/stern"
    dest: "/usr/local/bin/stern"
    state: link
  become: yes
