- when: ansible_pkg_mgr == "apt"
  block:
    - name: Get repo key
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
      become: yes

    - name: Add terraform repo
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        filename: hashicorp
        state: present
      become: yes

    - name: Install terraform
      ansible.builtin.apt:
        name: terraform
        update_cache: yes
      become: yes

- name: Enable autocomplete
  ansible.builtin.command: /usr/bin/zsh -c 'terraform -install-autocomplete'
